# vicon2gt configuration - Euroc Eth dataset parameters

# Use rosbag2 (directory) instead of CSV files
path_bag: /home/horclab/optitrack_client/go1_imu_optitrack_bag1

# Topic configuration
topic_imu: /imu
topic_vicon: /go1/pose

# Output paths (leave empty, will use dataset parameter from launch)
stats_path_states: /home/horclab/optitrack_client/go1_imu_optitrack_bag1/vicon2gt_output/go1_vicon2gt_states.csv
stats_path_info: /home/horclab/optitrack_client/go1_imu_optitrack_bag1/vicon2gt_output/go1_vicon2gt_info.txt

# Bag parameters
bag_start: 0
bag_durr: -1

# Output settings
state_freq: 240
save_to_file: true
use_manual_sigmas: true
freq_pub_raw_vicon: 1.0

# Calibration parameters (from exp_eth.launch)
R_BtoI: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
p_BinI: [0.0, 0.0, 0.0]
# R_GtoV: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
R_GtoV: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]


# World parameters
gravity_magnitude: 9.81
toff_imu_to_vicon: 0.0
num_loop_relin: 0
estimate_toff_vicon_to_imu: true
estimate_ori_vicon_to_imu: true
estimate_pos_vicon_to_imu: true

# Vicon sigmas (rx, ry, rz, px, py, pz)
vicon_sigmas: [1e-3, 1e-3, 1e-3, 1e-2, 1e-2, 1e-2]

# IMU noise parameters (GO1 IMU)
# gyroscope_noise_density: 0.0003244204920655747 
# gyroscope_random_walk: 1.2490694285178616e-06
# accelerometer_noise_density: 0.0018419808407498623 
# accelerometer_random_walk: 5.394210131046306e-05

# IMU noise parameters (GO1 IMU) x10 inflated
gyroscope_noise_density: 0.003244204920655747 
gyroscope_random_walk: 1.2490694285178616e-05
accelerometer_noise_density: 0.018419808407498623 
accelerometer_random_walk: 5.394210131046306e-04
